language: java
jdk:
- openjdk8

addons:
    sonarcloud:
        organization: "LeonardoMonnati96"
        token: 
            secure: d7c340793e9d835f003fb293ddc6e15db109c293
            
script: 
- ant build
- sonar-scanner
