language: java
jdk:
- openjdk8

addons:
  sonarcloud:
    organization:"leonardomonnati96"

    token:
      secure:bc9ac52acbf4ca71867cc570966c6f06e0be330e

script: 
- ant build 
- sonar-scanner